### ISSUE TITLE
[Checklist] Phase 1 - Support CNN on Keras with MXNet

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [awslabs/keras-apache-mxnet#7]
This issue is to track all the pending tasks to support CNN on Keras with MXNet backend.
(Note this is a running list)

- [X] bias_add
- [x] batch_norm
- [X] batch_dot
- [X] Conv2D
- [x] Conv2D_Transpose
- [X] Pooling2D
- [X] Able to create and stack layers sequentially
- [X] Able to compile the model
- [X] Able to fit
- [X] Supports CPU
- [X] Supports one GPU
- [X] Supports multi-GPU
- [X] Able to train Resnet50 on CIFAR10
- [X] SGD Optimizer
- [X] RMSProp Optimizer
- [x] Adam Optimizer
- [x] AdaDelta Optimizer
- [x] Able to train VGGNet on CIFAR10
- [x] Able to train InceptionV3 on CIFAR10
- [x] Able to save the model
- [x] Able to load the saved model (pre-trained with MXNet)
- [x] Able to run inference from pre-trained model
- [x] Keras tests are passing
- [x] Keras lint checks are passing
- [ ] Able to load the saved model (from other backend?)

**Comment by sandeep-krishnamurthy** [comment]
Resolving. All tasks are complete.
